version: 0.2


env:
  variables:
    IMAGE_URI: "799618983059.dkr.ecr.us-east-1.amazonaws.com/eks-demo/communitypro-portfolio-og"
  exported-variables:
    - IMAGE_URI
    - IMAGE_TAG


phases:
  install:
#    runtime-versions:
#      nodejs: 18
    commands:
    - echo "Install Phase - NOTHING TO DO "

  pre_build:
    commands:
    # Generate a short Docker image tag using github commit code. 
    - IMAGE_TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)"
    - export IMAGE_TAG
    # Authenticate Docker with ECR using AWS CLI
    - echo "Logging into Amazon ECR at $IMAGE_URI..."
    - aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_URI


  build:
    commands:
    # Build Docker image using Dockerfile in root directory
    - echo "Building Docker Image . . . . . "
    - docker build -t $IMAGE_URI:$IMAGE_TAG .

  post_build:
    commands:
    # Push the built Docker image to ECR repository
    - echo "Pushing Docker image to ECR..."
    - docker push $IMAGE_URI:$IMAGE_TAG
    # Export image metadata to be used in the deploy stage
    - echo "Exporting variables for downstream stages..."
    - echo "IMAGE_URI=$IMAGE_URI" >> $CODEBUILD_SRC_DIR/exported-vars.env
    - echo "IMAGE_TAG=$IMAGE_TAG" >> $CODEBUILD_SRC_DIR/exported-vars.env
  
artifacts:
  files:
    - exported-vars.env
    - buildspec-deploy.yml
    - '**/kube-manifests/**/*'